### ISSUE TITLE
Upload TEMP directory - how to change (LocalVolume) Debian, Apache, PHP

### ISSUE THREAD

**Issue by santaclaus21** [Studio-42/elFinder#1094]
I'm using elFinder with LocalVolume connector on Debian+Apache. My default upload temp dir is "/tmp" located on system partition. There is only 800MB free actualy. And this is a problem. 

1) While sending big file by elFinder, files is chunked to "/tmp" to 0 bytes free on partition. This is a big problem, because it's master partition. However I've got 28GB free in "/home" partition...
2) Second problem is elFinder not always delete these (temp) files.

I need to change upload temp dir, but I don't know how to do it. I was trying with:
- connector "'tmpPath' => '/home/mydir'" (with no result) and also with:
- replacing elFinder.class.php :1835 > $testDirs[] = sys_get_temp_dir(); with $testDirs[] = '/home/mydir' (with also not result).

Both of them wasn't working for my. I have to replace temp to /home... And I don't wan't to change default php upload temp dir (by php.ini). Please help!

**Comment by megadr01d** [comment]
Try to use a relative path from your `path` setting, eg.

```php
'path'    => '/home/webspace/public_html',
'tmpPath' => '../../../tmp' // OR
'tmpPath' => '../../../home/mytmpdir' // OR
'tmpPath' => '../../mytmpdir'
```

**Comment by santaclaus21** [comment]
I doesn't help. It looks like it has been ignored. I can see that temp files are still created in "/tmp".

**Comment by megadr01d** [comment]
If you're using v2.0, try [v2.1 nightly](https://github.com/nao-pon/elFinder-nightly). `tmpPath` is actually only included in [2.1's Wiki](https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#tmpPath) so maybe it was fixed.

**Comment by santaclaus21** [comment]
I'm using 2.1, now I tried also with nightly, without sucess... Still the same, elFinfer ignore my tmpPath.

**Comment by nao-pon** [comment]
@santaclaus21 , @megadr01d Thanks!

Added a new connector config `uploadTempPath` into 2.1 branch.

```php
$opts = array(
    'locale' => '',
    'uploadTempPath' => 'PATH TO UPLOAD TEMP',
    'roots'  => array(
        array(
            'driver' => 'LocalFileSystem',
            'path'   => '/path/to/files/',
            'URL'    => 'http://localhost/to/files/'
        )
    )
);
```

**Comment by santaclaus21** [comment]
So, @nao-pon what is a difference now between config "tmpPath" and "uploadTempPath" ?

**Comment by nao-pon** [comment]
@santaclaus21 option `uploadTempPath` is Main option, It is not Root option. ( https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1 )

`uploadTempPath`: Main option. It's shared by all volumes.
`tmpPath`: Each Root option. Temporary directory for extracts etc.

**Comment by nao-pon** [comment]
And I added error handling of chunked upload @1c005968360f7d4cb0e9baf3fc264d6d6ad88afd .

**Comment by santaclaus21** [comment]
ok, thanks.

**Comment by santaclaus21** [comment]
How to debug errors in elFinder ?

**Comment by nao-pon** [comment]
'uploadTempPath' is setting of elFinder temp files path. This file name has 'ELF' as prefix. Do you want control of PHP temp files (maybe has 'PHP' as prefix) path?

About debug

- use  `error_reporting(E_ALL);` and check server responce
- use `debug($target);` with next code in connector.php
```php
function debug($var) {
	ob_start();
	//debug_print_backtrace();
	var_dump($var);
	$out = ob_get_clean();
	file_put_contents('PATH_TO/debug.txt', $out . "\n", FILE_APPEND);
}
```

**Comment by santaclaus21** [comment]
Thank you. It was working fine "uploadTempPath" is working (but only for chunking). Firstly php send temp files to "upload_tmp_dir" in php.ini and then to "uploadTempPath". I have got also problem with files >2GB this is problem with 32bit OS probably. @nao-pon Thank you very much!
