### ISSUE TITLE
File upload returns wrong url

### ISSUE THREAD

**Issue by stalker780** [Studio-42/elFinder#3725]
Just updated to 2.1.66

https://github.com/Studio-42/elFinder/commit/7084b550a7ed2b25a667ca308ae368bcef64f214

After this commit url property returns wrong path in JSON.

Instead of 
`https://store1.loc/image/catalog/Samsung-3/philips_27m2n5500.webp`
I get 
`https://store1.loc/image/catalog/g/Samsung-3/philips_27m2n5500.webp`

Two excessive chars `/g` are inserted after the root url.

My root url is set to `https://store1.loc/image/catalog`. And it worked fine in 2.1.65.

This bug breaks the process of uploading + selecting new image. Cause I use `getFileCallback(file) { result = file.url }` to select latest uploaded image with double click.

After I reverted this line the url property works correctly again.

To reproduce this bug you need to drag&drop any file and check the JSON output of POST request:
My result is:
```
{
	"added": [
		{
			"isowner": false,
			"ts": 1756480901,
			"mime": "image\/webp",
			"read": 1,
			"write": 1,
			"size": "129244",
			"hash": "l1_U2Ftc3VuZy0zL3BoaWxpcHNfMjdtMm41NTAwLndlYnA",
			"name": "philips_27m2n5500.webp",
			"phash": "l1_U2Ftc3VuZy0z",
			"tmb": 1,
			"url": "https:\/\/store1.loc\/image\/catalog\/g\/Samsung-3\/philips_27m2n5500.webp"
		}
	],
	"removed": [],
	"changed": [
		{
			"isowner": false,
			"ts": 1756480901,
			"mime": "directory",
			"read": 1,
			"write": 1,
			"size": 0,
			"hash": "l1_U2Ftc3VuZy0z",
			"name": "Samsung-3",
			"phash": "l1_Lw",
			"volumeid": "l1_"
		}
	]
}
```

**Comment by JustinBack** [comment]
Can confirm, the same happens!

```php

                array(
                    'id'            => '1',
                    'driver'        => 'LocalFileSystem',
                    'path'          => core::PERSISTENT_DATA . '/files/',
                    'tmbPath'       => core::PERSISTENT_DATA . '/thumbnails/',
                    'tmbURL'        => "/assets/thumbnails/",
                    'trashHash'     => 't99_Lw',
                    'URL'           => "/assets/ugc/",
                    'winHashFix'    => DIRECTORY_SEPARATOR !== '/',
                    'uploadDeny'    => $this->forbiddenMimeTypes,
                    'uploadAllow'   => $this->allowedMimeTypes,
                    'uploadOrder'   => array('deny', 'allow'),
                    'accessControl' => 'access',
                    'attributes' => array(
                        array(
...
```

```json
{
    "added": [
        {
            "isowner": false,
            "ts": 1756748948,
            "mime": "image\/jpeg",
            "read": 1,
            "write": 1,
            "size": "2247537",
            "hash": "l1_dGVzdC9mYXJ6YWQtcC14U2wzM1d4eWMtdW5zcGxhc2guanBn",
            "name": "farzad-p-xSl33Wxyc-unsplash.jpg",
            "phash": "l1_dGVzdA",
            "tmb": 1,
            "url": "\/assets\/ugc\/s\/test\/farzad-p-xSl33Wxyc-unsplash.jpg" # <--- /s is wrong
        }
    ],
    "removed": [],
    "changed": [
        {
            "isowner": false,
            "ts": 1756748948,
            "mime": "directory",
            "read": 1,
            "write": 1,
            "size": 0,
            "hash": "l1_dGVzdA",
            "name": "test",
            "phash": "l1_Lw",
            "volumeid": "l1_"
        }
    ]
}
```

Refreshing the Dialog via F5 fixes the issue as it gets the correct url.

**Comment by egrefin** [comment]
Yes, same here!  
Uploading + selecting new file add 's/' in the defined root URL.

As indicated in #3667, in the php/elFinderVolumeDriver.class.php file of version 2.1.66, I replaced the new line 3334 with the old one: $path = str_replace($this->separator, ‘/’, substr($this->decode($hash), strlen(rtrim($this->root, ‘/’ . $this->separator)) + 1));
and it works again as before.

**Comment by santaclaus21** [comment]
Same for me, version 2.1.66 only

**Comment by JustinBack** [comment]
Here is a patch that should fix both the original issue and this one.

```patch
From ef0ad942d2b45cca4deb58b1653f970cefd1c4fd Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Justin=20Ren=C3=A9=20Back?= <justin.back@bl-netzwerke.de>
Date: Thu, 11 Sep 2025 02:42:57 +0200
Subject: [PATCH] Refactor URL path handling in elFinderVolumeDriver

---
 php/elFinderVolumeDriver.class.php | 20 ++++++++++++++++++--
 1 file changed, 18 insertions(+), 2 deletions(-)

diff --git a/php/elFinderVolumeDriver.class.php b/php/elFinderVolumeDriver.class.php
index 7df8d253b..a456c3414 100644
--- a/php/elFinderVolumeDriver.class.php
+++ b/php/elFinderVolumeDriver.class.php
@@ -3331,12 +3331,28 @@ public function getContentUrl($hash, $options = array())
             }
         }
         if (empty($file['url']) && $this->URL) {
-            $path = str_replace($this->separator, '/', substr($this->decode($hash), strlen(trim($this->root, '/' . $this->separator))));
+            $decoded = $this->decode($hash);
+
+            // safely strip root prefix if present
+            if (str_starts_with($decoded, $this->root)) {
+                $path = substr($decoded, strlen($this->root));
+            } else {
+                $path = $decoded;
+            }
+
+            // remove leading separator to avoid double slashes
+            $path = ltrim($path, '/');
+
+            // normalize separators
+            $path = str_replace($this->separator, '/', $path);
+
             if ($this->encoding) {
                 $path = $this->convEncIn($path, true);
             }
+
             $path = str_replace('%2F', '/', rawurlencode($path));
-            return $this->URL . $path;
+
+            return rtrim($this->URL, '/') . '/' . $path;
         } else {
             $ret = false;
             if (!empty($file['url']) && $file['url'] != 1) {
```

Test Results were good so far and I have published an updated version under my fork. https://packagist.org/packages/bl-netzwerke/elfinder

**Comment by BackNot** [comment]
Hi all , I have implemented temporary workaround for anyone that is interested. In the javascript where I make my elfinder instance in the callback on upload I do a reload.

```
 handlers: {
                upload: function (event, fm) {
                    fm.exec('reload');
                },
            },
```

docs: https://github.com/Studio-42/elFinder/wiki/Client-event-API

**Comment by instantflorian** [comment]
What a pity that this has not been corrected in the latest release :(

**Comment by stalker780** [comment]
I cannot reopen this issue. Only create a new one.
That's insane such a critical bug is not fixed for 9 months

**Comment by stalker780** [comment]
@instantflorian I have just checked the latest sources https://github.com/Studio-42/elFinder/tree/2.1
And it seems to be fixed there.
